### ISSUE TITLE
Logo styles don't match

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/react-example#1]
I noticed Bocadillo has a horizontal banner logo on the frontend's home page, while React has a square "atom" logo.

We do have a square "sandwich" logo which you can find [in the repo](https://github.com/bocadilloproject/bocadillo/blob/master/docs/art/sandwich_icon.png). I think it would look even better if we used the same kind of logo for both Bocadillo and React. :-)

**Comment by cs01** [comment]
I just pushed to master, but probably should have opened a PR. If it looks good feel free to close!

**Comment by florimondmanca** [comment]
Great! 👍
