### ISSUE TITLE
Example Out of Date and Confusing

### ISSUE THREAD

**Issue by benwis** [bocadilloproject/react-example#11]
The react example in master doesn't currently run, and appears to be missing requirements.txt. I'd recommend merging the react-apollo branch and updating that requirements.txt with the latest packages

**Comment by florimondmanca** [comment]
@benwis Thanks for reporting this! Do you have any tracebacks to get a sense of what kind of things are out of date? My initial guess is that the code isn't compatible with the latest version of Bocadillo (v0.18.x). Thanks!

**Comment by benwis** [comment]
Submitted a pull request for the necessary changes to make the example run
