### ISSUE TITLE
add hot reloading to server

### ISSUE THREAD

**Issue by cs01** [bocadilloproject/react-example#6]
I recently updated the example to make an api call to fetch a message from Bocadillo and display it in the frontend. If I edit the message on the server and reload the webpage, nothing happens because Bocadillo is still serving the same API code.

@florimondmanca what is the best way to get the server to hot reload on changes? I recall you saying something about modifying the "right way" to enter dev mode since Bocadillo will rely more on the underlying ASGI API's.

**Comment by florimondmanca** [comment]
In 0.13 you should run with app.run(debug=True) to enable hot reload. But I found there tends to be a weird memory leak doing that.

So I would recommend changing the way the app is served altogether and use uvicorn with the reload flag:

uvicorn app:app --reload

This will be the official and unique way of running apps starting from 0.14. :)

**Comment by cs01** [comment]
Okay I will wait until 0.14 is released. 

+1 for having a single way canonical way to serve Bocadillo.

**Comment by florimondmanca** [comment]
Alright! FYI the uvicorn command will work 100% fine since that’s what app.run(debug=True) does behind the scenes. :-)

**Comment by cs01** [comment]
Oh okay, so no need to wait?

**Comment by florimondmanca** [comment]
Nope! Give it a shot to be sure, but I think this is going to work just fine. 😄

**Comment by cs01** [comment]
Updated readme
